# Generated by Django 3.1.7 on 2021-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enquiry',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
