# Generated by Django 3.1.7 on 2021-03-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'News and Update', 'verbose_name_plural': 'News and Update'},
        ),
    ]
