# Generated by Django 3.1.7 on 2021-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_update', '0002_auto_20210305_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
