# Generated by Django 3.1.7 on 2021-03-02 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
